import { BsFillTelephoneFill, BsMessenger, BsGithub } from "react-icons/bs";
import { SiGmail } from "react-icons/si";

export const meal = [
  {
    id: 1,
    name: "Sisig",
    category: "meal",
    likes: [],
    disLikes: [],
    comments: [],
    mainIngredient: "Pork",
    img: [
      "https://scm-assets.constant.co/scm/unilever/f4b5026fe1dd6b46672ba349cfbb04e4/f0aeb360-b9d0-4fe1-8a42-e32998053276.jpg",
      "https://previews.123rf.com/images/cokemomo/cokemomo1611/cokemomo161100044/66029711-sizzling-pork-sisig-filipino-cuisine.jpg",
      "https://www.foxyfolksy.com/wp-content/uploads/2015/05/Sizzling-Sisig-640.jpg",
      "https://cdn.i-scmp.com/sites/default/files/styles/1920x1080/public/d8/images/2019/09/18/scmp_16apr15_fe_foodshoot7_jonw6710.jpg?itok=fxxTr-Bv",
    ],
    info: `The dish's name comes from “sisigan,” an old Tagalog word which means “to make it sour.” 
    Its existence was first recorded in a Kapampangan dictionary back in 1732 by Diego Bergaño,
     a Spanish missionary who served as the parish priest for Mexico, Pampanga at the time.`,
    recipe: [
      { amount: "1lb", name: "pig ears" },
      { amount: "1 1/2 lb ", name: "pork belly" },
      { amount: "1 piece ", name: "onion minced" },
      { amount: "3 tablespoons", name: "soy sauce" },
      { amount: "1/4 teaspoon", name: "ground black pepper" },
      { amount: "1 knob ", name: "ginger minced (optional)" },
      { amount: "3 tablespoons ", name: "chili flakes" },
      { amount: "1/2 teaspoon", name: "garlic powder" },
      { amount: "1 piece ", name: "lemon" },
      { amount: "½ cup ", name: "butter" },
      { amount: "¼ lb  ", name: "chicken liver" },
    ],
    procedure: [
      "Pour the water in a pan and bring to a boil Add salt and pepper.",
      "Put-in the pig's ears and pork belly then simmer for 40 minutes to 1 hour",
      "Remove the boiled ingredients from the pot then drain excess water",
      "Grill the boiled pig ears and pork belly until done",
      "Chop the pig ears and pork belly into fine pieces",
      "In a wide pan, melt the butter or margarine. Add the onions. Cook until onions are soft.",
      "Put-in the ginger and cook for 2 minutes",
      "Add the chicken liver. Crush the chicken liver while cooking it in the pan.",
      "Add the chopped pig ears and pork belly. Cook for 10 to 12 minutes",
      "Put-in the soy sauce, garlic powder, and chili. Mix well",
      "Add salt and pepper to taste",
      "Put-in the mayonnaise and mix with the other ingredients",
      "Transfer to a serving plate. Top with chopped green onions and raw egg.",
      "Serve hot. Share and Enjoy (add the lemon or calamansi before eating)",
    ],
  },
  {
    id: 2,
    name: "sinigang na baboy",
    category: "meal",
    likes: [],
    disLikes: [],
    comments: [],
    mainIngredient: "Pork",
    img: [
      "https://www.kawalingpinoy.com/wp-content/uploads/2013/01/sinigang-baboy-7-768x1024.jpg",
      "https://www.bitemybun.com/wp-content/uploads/2020/09/Sinigang-na-Baboy-Recipe-Pork-Sinigang.jpg",
      "https://images.saymedia-content.com/.image/t_share/MTc0Nzc4MjE4ODMyNzMzOTY3/sinigang-na-baboy-filipino-pork-sinigang.png",
      "https://i.pinimg.com/originals/74/21/0a/74210a9943101beb01df5cba885465a3.jpg",
    ],
    info: `Sinigang is a dish originated in the Philippines. Typically, it is composed of fish, meat, 
    vegetables, tomatoes and tamarind flavoring. The reason why it is called “sinigang” is that it was a 
    translation to the English word, “stew” which is true because of its method of cooking.`,
    recipe: [
      { amount: "1lb", name: "pig ears" },
      { amount: "1 1/2 lb ", name: "pork belly" },
      { amount: "1 piece ", name: "onion minced" },
      { amount: "3 tablespoons", name: "soy sauce" },
      { amount: "1/4 teaspoon", name: "ground black pepper" },
      { amount: "1 knob ", name: "ginger minced (optional)" },
      { amount: "3 tablespoons ", name: "chili flakes" },
      { amount: "1/2 teaspoon", name: "garlic powder" },
      { amount: "1 piece ", name: "lemon" },
      { amount: "½ cup ", name: "butter" },
      { amount: "¼ lb  ", name: "chicken liver" },
    ],
    procedure: [
      "Pour the water in a pan and bring to a boil Add salt and pepper.",
      "Put-in the pig's ears and pork belly then simmer for 40 minutes to 1 hour",
      "Remove the boiled ingredients from the pot then drain excess water",
      "Grill the boiled pig ears and pork belly until done",
      "Chop the pig ears and pork belly into fine pieces",
      "In a wide pan, melt the butter or margarine. Add the onions. Cook until onions are soft.",
      "Put-in the ginger and cook for 2 minutes",
      "Add the chicken liver. Crush the chicken liver while cooking it in the pan.",
      "Add the chopped pig ears and pork belly. Cook for 10 to 12 minutes",
      "Put-in the soy sauce, garlic powder, and chili. Mix well",
      "Add salt and pepper to taste",
      "Put-in the mayonnaise and mix with the other ingredients",
      "Transfer to a serving plate. Top with chopped green onions and raw egg.",
      "Serve hot. Share and Enjoy (add the lemon or calamansi before eating)",
    ],
  },
  {
    id: 3,
    name: "adobong manok",
    category: "meal",
    likes: [],
    disLikes: [],
    comments: [],
    mainIngredient: "Chicken",
    img: [
      "https://lolakusinera.com/wp-content/uploads/2019/01/adobo-chicken.jpg",
      "https://img-global.cpcdn.com/recipes/3618ba4406fe59c3/1200x630cq70/photo.jpg",
      "https://recipetineats.com/wp-content/uploads/2015/02/Filipino-Chicken-Adobo_6.jpg",
      "https://rasamalaysia.com/wp-content/uploads/2013/05/chicken-adobo-thumb.jpg",
    ],
    info: `The word adobo is derived from the Spanish word adobar, which means “marinade” or 
    pickling sauce.” The existence of the tangy dish was first recorded in 1613 by the Spaniard
     Pedro de San Buenaventura. ... The Chinese traders who later visited our islands introduced soy sauce to early Filipinos.`,
    recipe: [
      { amount: "1lb", name: "pig ears" },
      { amount: "1 1/2 lb ", name: "pork belly" },
      { amount: "1 piece ", name: "onion minced" },
      { amount: "3 tablespoons", name: "soy sauce" },
      { amount: "1/4 teaspoon", name: "ground black pepper" },
      { amount: "1 knob ", name: "ginger minced (optional)" },
      { amount: "3 tablespoons ", name: "chili flakes" },
      { amount: "1/2 teaspoon", name: "garlic powder" },
      { amount: "1 piece ", name: "lemon" },
      { amount: "½ cup ", name: "butter" },
      { amount: "¼ lb  ", name: "chicken liver" },
    ],
    procedure: [
      "Pour the water in a pan and bring to a boil Add salt and pepper.",
      "Put-in the pig's ears and pork belly then simmer for 40 minutes to 1 hour",
      "Remove the boiled ingredients from the pot then drain excess water",
      "Grill the boiled pig ears and pork belly until done",
      "Chop the pig ears and pork belly into fine pieces",
      "In a wide pan, melt the butter or margarine. Add the onions. Cook until onions are soft.",
      "Put-in the ginger and cook for 2 minutes",
      "Add the chicken liver. Crush the chicken liver while cooking it in the pan.",
      "Add the chopped pig ears and pork belly. Cook for 10 to 12 minutes",
      "Put-in the soy sauce, garlic powder, and chili. Mix well",
      "Add salt and pepper to taste",
      "Put-in the mayonnaise and mix with the other ingredients",
      "Transfer to a serving plate. Top with chopped green onions and raw egg.",
      "Serve hot. Share and Enjoy (add the lemon or calamansi before eating)",
    ],
  },

  {
    id: 4,
    name: "tinolang Manok",
    category: "meal",
    likes: [],
    disLikes: [],
    comments: [],
    mainIngredient: "Chicken",
    img: [
      "https://www.friendcheapmenu.com/wp-content/uploads/2021/05/tm-wp.jpg",
      "https://www.rivertenkitchen.com/wp-content/uploads/2020/11/Filipino-Chicken-Tinola-180355-500x500.jpg",
      "https://static.rivertenkitchen.com/wp-content/uploads/2020/11/Tinolang-Manok-Recipe-3-180363-1200x1600.jpg",
      "https://static.rivertenkitchen.com/wp-content/uploads/2020/11/Chicken-Tinola-Recipe-2-180389-1200x1600.jpg",
    ],
    info: `The history and influence of Tinolang Manok dates back during the Song Dynasty in China.
     It was another food item that was developed due to cultural contact with China via trade routes
      between 960 and 1279. The Chinese 
    traders are good herbalist and they know well the curative factor and health benefits of ginger.`,
    recipe: [
      { amount: "1lb", name: "pig ears" },
      { amount: "1 1/2 lb ", name: "pork belly" },
      { amount: "1 piece ", name: "onion minced" },
      { amount: "3 tablespoons", name: "soy sauce" },
      { amount: "1/4 teaspoon", name: "ground black pepper" },
      { amount: "1 knob ", name: "ginger minced (optional)" },
      { amount: "3 tablespoons ", name: "chili flakes" },
      { amount: "1/2 teaspoon", name: "garlic powder" },
      { amount: "1 piece ", name: "lemon" },
      { amount: "½ cup ", name: "butter" },
      { amount: "¼ lb  ", name: "chicken liver" },
    ],
    procedure: [
      "Pour the water in a pan and bring to a boil Add salt and pepper.",
      "Put-in the pig's ears and pork belly then simmer for 40 minutes to 1 hour",
      "Remove the boiled ingredients from the pot then drain excess water",
      "Grill the boiled pig ears and pork belly until done",
      "Chop the pig ears and pork belly into fine pieces",
      "In a wide pan, melt the butter or margarine. Add the onions. Cook until onions are soft.",
      "Put-in the ginger and cook for 2 minutes",
      "Add the chicken liver. Crush the chicken liver while cooking it in the pan.",
      "Add the chopped pig ears and pork belly. Cook for 10 to 12 minutes",
      "Put-in the soy sauce, garlic powder, and chili. Mix well",
      "Add salt and pepper to taste",
      "Put-in the mayonnaise and mix with the other ingredients",
      "Transfer to a serving plate. Top with chopped green onions and raw egg.",
      "Serve hot. Share and Enjoy (add the lemon or calamansi before eating)",
    ],
  },
  {
    id: 6,
    name: "Nilagang baka",
    category: "meal",
    likes: [],
    disLikes: [],
    comments: [],
    mainIngredient: "Beef",
    img: [
      "https://i.pinimg.com/736x/c9/d0/c5/c9d0c53ed23e5503c47a00082278875c.jpg",
      "https://i.pinimg.com/originals/f9/f3/cf/f9f3cf2a5b361c6a42323a7616ff4ea6.jpg",
      "https://www.foxyfolksy.com/wp-content/uploads/2017/06/nilagang-baka-recipe-640.jpg",
      "https://static.rivertenkitchen.com/wp-content/uploads/2019/05/Beef-Nilaga-p.jpg",
    ],
    info: `History of Nilagang Baka can be traced way back during the pre-Hispanic or pre-colonial
     era when the Austronesians, people from Southeast Asia and Pacific, brought with them their simple 
     cooking method of boiling in the Philippines. Nilagang Baka is a 
    Tagalog term simply translated in English as "Boiled Beef".`,
    recipe: [
      { amount: "1lb", name: "pig ears" },
      { amount: "1 1/2 lb ", name: "pork belly" },
      { amount: "1 piece ", name: "onion minced" },
      { amount: "3 tablespoons", name: "soy sauce" },
      { amount: "1/4 teaspoon", name: "ground black pepper" },
      { amount: "1 knob ", name: "ginger minced (optional)" },
      { amount: "3 tablespoons ", name: "chili flakes" },
      { amount: "1/2 teaspoon", name: "garlic powder" },
      { amount: "1 piece ", name: "lemon" },
      { amount: "½ cup ", name: "butter" },
      { amount: "¼ lb  ", name: "chicken liver" },
    ],
    procedure: [
      "Pour the water in a pan and bring to a boil Add salt and pepper.",
      "Put-in the pig's ears and pork belly then simmer for 40 minutes to 1 hour",
      "Remove the boiled ingredients from the pot then drain excess water",
      "Grill the boiled pig ears and pork belly until done",
      "Chop the pig ears and pork belly into fine pieces",
      "In a wide pan, melt the butter or margarine. Add the onions. Cook until onions are soft.",
      "Put-in the ginger and cook for 2 minutes",
      "Add the chicken liver. Crush the chicken liver while cooking it in the pan.",
      "Add the chopped pig ears and pork belly. Cook for 10 to 12 minutes",
      "Put-in the soy sauce, garlic powder, and chili. Mix well",
      "Add salt and pepper to taste",
      "Put-in the mayonnaise and mix with the other ingredients",
      "Transfer to a serving plate. Top with chopped green onions and raw egg.",
      "Serve hot. Share and Enjoy (add the lemon or calamansi before eating)",
    ],
  },
  {
    id: 5,
    name: "Afritadang manok",
    category: "meal",
    likes: [],
    disLikes: [],
    comments: [],
    mainIngredient: "Chicken",
    img: [
      "https://www.panlasangpinoyrecipes.com/wp-content/uploads/2015/11/Afritadang-Manok-Chiken-Afritada.jpg",
      "https://panlasangpinoy.com/wp-content/uploads/2018/12/How-to-Cook-Chicken-Afritada-500x500.jpg",
      "https://static.rivertenkitchen.com/wp-content/uploads/2020/02/How-to-cook-best-Filipino-Chicken-Afritada.jpg",
      "https://i.pinimg.com/736x/d0/f6/9b/d0f69b31c69d0dab2c6095307955e1ab.jpg",
    ],
    info: `The origin of this delicious Filipino dish dates back during the colonial era (1521-1898) of Spain 
    in the Philippines.In fact, Afritada was derived from the Spanish word “fritada” 
    which means “fried”.`,
    recipe: [
      { amount: "1lb", name: "pig ears" },
      { amount: "1 1/2 lb ", name: "pork belly" },
      { amount: "1 piece ", name: "onion minced" },
      { amount: "3 tablespoons", name: "soy sauce" },
      { amount: "1/4 teaspoon", name: "ground black pepper" },
      { amount: "1 knob ", name: "ginger minced (optional)" },
      { amount: "3 tablespoons ", name: "chili flakes" },
      { amount: "1/2 teaspoon", name: "garlic powder" },
      { amount: "1 piece ", name: "lemon" },
      { amount: "½ cup ", name: "butter" },
      { amount: "¼ lb  ", name: "chicken liver" },
    ],
    procedure: [
      "Pour the water in a pan and bring to a boil Add salt and pepper.",
      "Put-in the pig's ears and pork belly then simmer for 40 minutes to 1 hour",
      "Remove the boiled ingredients from the pot then drain excess water",
      "Grill the boiled pig ears and pork belly until done",
      "Chop the pig ears and pork belly into fine pieces",
      "In a wide pan, melt the butter or margarine. Add the onions. Cook until onions are soft.",
      "Put-in the ginger and cook for 2 minutes",
      "Add the chicken liver. Crush the chicken liver while cooking it in the pan.",
      "Add the chopped pig ears and pork belly. Cook for 10 to 12 minutes",
      "Put-in the soy sauce, garlic powder, and chili. Mix well",
      "Add salt and pepper to taste",
      "Put-in the mayonnaise and mix with the other ingredients",
      "Transfer to a serving plate. Top with chopped green onions and raw egg.",
      "Serve hot. Share and Enjoy (add the lemon or calamansi before eating)",
    ],
  },
  {
    id: 12,
    name: "lumpiang Shanghai",
    category: "meal",
    likes: [],
    disLikes: [],
    comments: [],
    mainIngredient: "Pork",
    img: [
      "https://omnivorescookbook.com/wp-content/uploads/2020/12/201113_Lumpia-Shanghai_550.jpg",
      "https://www.foxyfolksy.com/wp-content/uploads/2014/12/lumpiang-shanghai-640.jpg",
      "https://cdn.tasteatlas.com/Images/Dishes/5130e26a68774a7285b845398173d9c1.jpg?w=600&h=450",
      "https://cdn.tasteatlas.com/images/dishes/4f8fa81ab1a5429c849fca30a7aa786c.jpg",
    ],
    info: `The name lumpiang Shanghai hints at the Chinese origin of lumpia, which first traveled to the 
    Philippines with ninth-century Chinese traders. ... Lumpia are also popular in Indonesia and even migrated
    via Dutch colonialism to the Netherlands, 
    where they grew larger and became a one-dish meal called loempia.`,
    recipe: [
      { amount: "1lb", name: "pig ears" },
      { amount: "1 1/2 lb ", name: "pork belly" },
      { amount: "1 piece ", name: "onion minced" },
      { amount: "3 tablespoons", name: "soy sauce" },
      { amount: "1/4 teaspoon", name: "ground black pepper" },
      { amount: "1 knob ", name: "ginger minced (optional)" },
      { amount: "3 tablespoons ", name: "chili flakes" },
      { amount: "1/2 teaspoon", name: "garlic powder" },
      { amount: "1 piece ", name: "lemon" },
      { amount: "½ cup ", name: "butter" },
      { amount: "¼ lb  ", name: "chicken liver" },
    ],
    procedure: [
      "Pour the water in a pan and bring to a boil Add salt and pepper.",
      "Put-in the pig's ears and pork belly then simmer for 40 minutes to 1 hour",
      "Remove the boiled ingredients from the pot then drain excess water",
      "Grill the boiled pig ears and pork belly until done",
      "Chop the pig ears and pork belly into fine pieces",
      "In a wide pan, melt the butter or margarine. Add the onions. Cook until onions are soft.",
      "Put-in the ginger and cook for 2 minutes",
      "Add the chicken liver. Crush the chicken liver while cooking it in the pan.",
      "Add the chopped pig ears and pork belly. Cook for 10 to 12 minutes",
      "Put-in the soy sauce, garlic powder, and chili. Mix well",
      "Add salt and pepper to taste",
      "Put-in the mayonnaise and mix with the other ingredients",
      "Transfer to a serving plate. Top with chopped green onions and raw egg.",
      "Serve hot. Share and Enjoy (add the lemon or calamansi before eating)",
    ],
  },
  {
    id: 13,
    name: "Paksiw na bangus",
    category: "meal",
    likes: [],
    disLikes: [],
    comments: [],
    mainIngredient: "Fish",
    img: [
      "http://images.summitmedia-digital.com/yummyph/images/2016/January_2016/PaksiwNaIsda-640.jpg",
      "https://asianfoodnetwork.com/content/dam/afn/global/en/recipes/paksiw-na-isda/AFN_paksiw_na_isda_main_image.jpg",
      "https://api.lifegetsbetter.ph/uploads/recipes/featured/pina-paksiw-na-bangus.jpg",
      "https://usapangfoodtrip.com/wp-content/uploads/2021/04/126951894_3314414615350820_8525656553695907162_n.jpg",
    ],
    info: `The name of the dish is derived from the word “paksiw” which is a cooking method where meat or 
    seafood is simmered in vinegar hence you will see this term not only used on fish but also pork. Paksiw na 
    Isda is a type of Filipino dish where fish is poached in vinegar seasoned with fish sauce and finger chillies`,
    recipe: [
      { amount: "1lb", name: "pig ears" },
      { amount: "1 1/2 lb ", name: "pork belly" },
      { amount: "1 piece ", name: "onion minced" },
      { amount: "3 tablespoons", name: "soy sauce" },
      { amount: "1/4 teaspoon", name: "ground black pepper" },
      { amount: "1 knob ", name: "ginger minced (optional)" },
      { amount: "3 tablespoons ", name: "chili flakes" },
      { amount: "1/2 teaspoon", name: "garlic powder" },
      { amount: "1 piece ", name: "lemon" },
      { amount: "½ cup ", name: "butter" },
      { amount: "¼ lb  ", name: "chicken liver" },
    ],
    procedure: [
      "Pour the water in a pan and bring to a boil Add salt and pepper.",
      "Put-in the pig's ears and pork belly then simmer for 40 minutes to 1 hour",
      "Remove the boiled ingredients from the pot then drain excess water",
      "Grill the boiled pig ears and pork belly until done",
      "Chop the pig ears and pork belly into fine pieces",
      "In a wide pan, melt the butter or margarine. Add the onions. Cook until onions are soft.",
      "Put-in the ginger and cook for 2 minutes",
      "Add the chicken liver. Crush the chicken liver while cooking it in the pan.",
      "Add the chopped pig ears and pork belly. Cook for 10 to 12 minutes",
      "Put-in the soy sauce, garlic powder, and chili. Mix well",
      "Add salt and pepper to taste",
      "Put-in the mayonnaise and mix with the other ingredients",
      "Transfer to a serving plate. Top with chopped green onions and raw egg.",
      "Serve hot. Share and Enjoy (add the lemon or calamansi before eating)",
    ],
  },
  {
    id: 20,
    name: "Bulalo",
    category: "meal",
    likes: [],
    disLikes: [],
    comments: [],
    mainIngredient: "Beef",
    img: [
      "https://www.kawalingpinoy.com/wp-content/uploads/2013/11/bulalo51.jpg",
      "https://chiboganna.com/wp-content/uploads/2020/05/bulalo-3.jpg",
      "https://tastecooking.com/wp-content/uploads/2018/05/Bulalo001.jpg",
      "https://i2.wp.com/www.foodwithmae.com/wp-content/uploads/2019/01/BeefBulaloMaeRecipe.jpg?fit=2548%2C2506",
    ],
    info: `Bulalô is a beef dish from the Philippines. It is a light colored soup that is made by cooking beef 
    shanks and bone marrow until the collagen and fat has melted into the clear broth. ...
    Bulalo is native to the Southern Luzon region of the Philippines, 
    particularly in the provinces of Batangas and Cavite.`,
    recipe: [
      { amount: "1lb", name: "pig ears" },
      { amount: "1 1/2 lb ", name: "pork belly" },
      { amount: "1 piece ", name: "onion minced" },
      { amount: "3 tablespoons", name: "soy sauce" },
      { amount: "1/4 teaspoon", name: "ground black pepper" },
      { amount: "1 knob ", name: "ginger minced (optional)" },
      { amount: "3 tablespoons ", name: "chili flakes" },
      { amount: "1/2 teaspoon", name: "garlic powder" },
      { amount: "1 piece ", name: "lemon" },
      { amount: "½ cup ", name: "butter" },
      { amount: "¼ lb  ", name: "chicken liver" },
    ],
    procedure: [
      "Pour the water in a pan and bring to a boil Add salt and pepper.",
      "Put-in the pig's ears and pork belly then simmer for 40 minutes to 1 hour",
      "Remove the boiled ingredients from the pot then drain excess water",
      "Grill the boiled pig ears and pork belly until done",
      "Chop the pig ears and pork belly into fine pieces",
      "In a wide pan, melt the butter or margarine. Add the onions. Cook until onions are soft.",
      "Put-in the ginger and cook for 2 minutes",
      "Add the chicken liver. Crush the chicken liver while cooking it in the pan.",
      "Add the chopped pig ears and pork belly. Cook for 10 to 12 minutes",
      "Put-in the soy sauce, garlic powder, and chili. Mix well",
      "Add salt and pepper to taste",
      "Put-in the mayonnaise and mix with the other ingredients",
      "Transfer to a serving plate. Top with chopped green onions and raw egg.",
      "Serve hot. Share and Enjoy (add the lemon or calamansi before eating)",
    ],
  },
  {
    id: 24,
    name: "Beef calderita",
    category: "meal",
    likes: [],
    disLikes: [],
    comments: [],
    mainIngredient: "Beef",
    img: [
      "https://speedyrecipe.com/wp-content/uploads/2016/09/Filipino-Beef-Kaldereta-Recipe.jpg",
      "https://1.bp.blogspot.com/-cBzU_RrT1fo/XS6pR1ugZaI/AAAAAAAATec/f_UPfQobDeskTsJHbMwEbFF-sC0h33gZQCLcBGAs/s1600/1.jpg",
      "https://chiboganna.com/wp-content/uploads/2020/04/beef-kaldereta.jpg",
      "https://1.bp.blogspot.com/-cBzU_RrT1fo/XS6pR1ugZaI/AAAAAAAATec/f_UPfQobDeskTsJHbMwEbFF-sC0h33gZQCLcBGAs/s1600/1.jpg",
    ],
    info: `Caldereta's name is derived from the Spanish word caldera meaning cauldron. 
    The dish is similar to meat stews from the Iberian Peninsula and was brought to the 
    Philippines by the Spaniards during their 300-year occupation of the Philippines.`,
    recipe: [
      { amount: "1lb", name: "pig ears" },
      { amount: "1 1/2 lb ", name: "pork belly" },
      { amount: "1 piece ", name: "onion minced" },
      { amount: "3 tablespoons", name: "soy sauce" },
      { amount: "1/4 teaspoon", name: "ground black pepper" },
      { amount: "1 knob ", name: "ginger minced (optional)" },
      { amount: "3 tablespoons ", name: "chili flakes" },
      { amount: "1/2 teaspoon", name: "garlic powder" },
      { amount: "1 piece ", name: "lemon" },
      { amount: "½ cup ", name: "butter" },
      { amount: "¼ lb  ", name: "chicken liver" },
    ],
    procedure: [
      "Pour the water in a pan and bring to a boil Add salt and pepper.",
      "Put-in the pig's ears and pork belly then simmer for 40 minutes to 1 hour",
      "Remove the boiled ingredients from the pot then drain excess water",
      "Grill the boiled pig ears and pork belly until done",
      "Chop the pig ears and pork belly into fine pieces",
      "In a wide pan, melt the butter or margarine. Add the onions. Cook until onions are soft.",
      "Put-in the ginger and cook for 2 minutes",
      "Add the chicken liver. Crush the chicken liver while cooking it in the pan.",
      "Add the chopped pig ears and pork belly. Cook for 10 to 12 minutes",
      "Put-in the soy sauce, garlic powder, and chili. Mix well",
      "Add salt and pepper to taste",
      "Put-in the mayonnaise and mix with the other ingredients",
      "Transfer to a serving plate. Top with chopped green onions and raw egg.",
      "Serve hot. Share and Enjoy (add the lemon or calamansi before eating)",
    ],
  },
];

export const Dessert = [
  {
    id: 9,
    name: "leche flan",
    category: "dessert",
    likes: [],
    disLikes: [],
    comments: [],
    mainIngredient: "egg",
    img: [
      "https://www.foxyfolksy.com/wp-content/uploads/2017/02/leche-flan-t1-500x375.jpg",
      "https://asliceofkate.com/wp-content/uploads/2020/05/img_20190217_005927_278-1.jpg?w=1024",
      "https://images.food52.com/gVOxFZy8xuiOJMq4-3RDEYXKyXY=/1200x900/0206d497-fd01-49ed-b1eb-5579fd39ee89--2019-0618_leche-flan_3x2_bobbi-lin_3974.jpg",
      "https://www.thespruceeats.com/thmb/QgT-WjX0_aXZ8I40mx-9OlnZBBw=/1000x1000/smart/filters:no_upscale()/filipino-leche-flan-recipe-3030303-14-5b3fcf0e46e0fb0037948091.jpg",
    ],
    info: `Originally, it was brought over to the Philippines during the Spanish colonization,
     so it is believed that it has origins in the regions on the border of Spain and France. Today, apart 
     from being consumed on its own as a sweet treat,
     pieces of leche flan can also be added to halo-halo, another popular Filipino dessert.`,
    recipe: [
      { amount: "1lb", name: "pig ears" },
      { amount: "1 1/2 lb ", name: "pork belly" },
      { amount: "1 piece ", name: "onion minced" },
      { amount: "3 tablespoons", name: "soy sauce" },
      { amount: "1/4 teaspoon", name: "ground black pepper" },
      { amount: "1 knob ", name: "ginger minced (optional)" },
      { amount: "3 tablespoons ", name: "chili flakes" },
      { amount: "1/2 teaspoon", name: "garlic powder" },
      { amount: "1 piece ", name: "lemon" },
      { amount: "½ cup ", name: "butter" },
      { amount: "¼ lb  ", name: "chicken liver" },
    ],
    procedure: [
      "Pour the water in a pan and bring to a boil Add salt and pepper.",
      "Put-in the pig's ears and pork belly then simmer for 40 minutes to 1 hour",
      "Remove the boiled ingredients from the pot then drain excess water",
      "Grill the boiled pig ears and pork belly until done",
      "Chop the pig ears and pork belly into fine pieces",
      "In a wide pan, melt the butter or margarine. Add the onions. Cook until onions are soft.",
      "Put-in the ginger and cook for 2 minutes",
      "Add the chicken liver. Crush the chicken liver while cooking it in the pan.",
      "Add the chopped pig ears and pork belly. Cook for 10 to 12 minutes",
      "Put-in the soy sauce, garlic powder, and chili. Mix well",
      "Add salt and pepper to taste",
      "Put-in the mayonnaise and mix with the other ingredients",
      "Transfer to a serving plate. Top with chopped green onions and raw egg.",
      "Serve hot. Share and Enjoy (add the lemon or calamansi before eating)",
    ],
  },
  {
    id: 14,
    name: "Maja blance",
    category: "dessert",
    likes: [],
    disLikes: [],
    comments: [],
    mainIngredient: "Coconut Milk",
    img: [
      "https://theunlikelybaker.com/wp-content/uploads/2020/09/Maja-Blanca-Recipe-4-776x1024.jpg.webp",
      "https://www.kawalingpinoy.com/wp-content/uploads/2013/03/maja-blanca-4-1-500x500.jpg",
      "https://asianfoodnetwork.com/content/dam/afn/global/en/recipes/maja-blanca/AFN_maja_blanca_main_image.jpg",
      "https://www.foxyfolksy.com/wp-content/uploads/2015/05/maja-blanca-640.jpg",
    ],
    info: `Maja Blanca has a rich historical background having originated from Spain and was adapted from the 
    traditional Spanish holiday referred to as manjar blanco, which actually means white delicacy`,
    recipe: [
      { amount: "1lb", name: "pig ears" },
      { amount: "1 1/2 lb ", name: "pork belly" },
      { amount: "1 piece ", name: "onion minced" },
      { amount: "3 tablespoons", name: "soy sauce" },
      { amount: "1/4 teaspoon", name: "ground black pepper" },
      { amount: "1 knob ", name: "ginger minced (optional)" },
      { amount: "3 tablespoons ", name: "chili flakes" },
      { amount: "1/2 teaspoon", name: "garlic powder" },
      { amount: "1 piece ", name: "lemon" },
      { amount: "½ cup ", name: "butter" },
      { amount: "¼ lb  ", name: "chicken liver" },
    ],
    procedure: [
      "Pour the water in a pan and bring to a boil Add salt and pepper.",
      "Put-in the pig's ears and pork belly then simmer for 40 minutes to 1 hour",
      "Remove the boiled ingredients from the pot then drain excess water",
      "Grill the boiled pig ears and pork belly until done",
      "Chop the pig ears and pork belly into fine pieces",
      "In a wide pan, melt the butter or margarine. Add the onions. Cook until onions are soft.",
      "Put-in the ginger and cook for 2 minutes",
      "Add the chicken liver. Crush the chicken liver while cooking it in the pan.",
      "Add the chopped pig ears and pork belly. Cook for 10 to 12 minutes",
      "Put-in the soy sauce, garlic powder, and chili. Mix well",
      "Add salt and pepper to taste",
      "Put-in the mayonnaise and mix with the other ingredients",
      "Transfer to a serving plate. Top with chopped green onions and raw egg.",
      "Serve hot. Share and Enjoy (add the lemon or calamansi before eating)",
    ],
  },

  {
    id: 7,
    name: "halo halo",
    category: "dessert",
    likes: [],
    disLikes: [],
    comments: [],
    mainIngredient: "Milk",
    img: [
      "https://www.lutongpinoyrecipe.com/wp-content/uploads/2021/02/lutong-pinoy-halo-halo-3-1200x1200.jpg",
      "https://i2.wp.com/chawjcreations.com/wp-content/uploads/2020/07/IMG_8011.jpg?fit=2553%2C1436&ssl=1",
      "https://upload.wikimedia.org/wikipedia/commons/3/30/Halo_halo1.jpg",
      "https://www.lutongbahayrecipe.com/wp-content/uploads/2019/03/lutong-bahay-halo-halo-1-1200x1355.jpg",
    ],
    info: `The origin of halo-halo is traced to the pre-war Japanese Filipinos and the Japanese kakigōri class 
    of desserts. ... Over time, more native ingredients were added, 
    resulting in the creation and development of the modern halo-halo.`,
    recipe: [
      { amount: "1lb", name: "pig ears" },
      { amount: "1 1/2 lb ", name: "pork belly" },
      { amount: "1 piece ", name: "onion minced" },
      { amount: "3 tablespoons", name: "soy sauce" },
      { amount: "1/4 teaspoon", name: "ground black pepper" },
      { amount: "1 knob ", name: "ginger minced (optional)" },
      { amount: "3 tablespoons ", name: "chili flakes" },
      { amount: "1/2 teaspoon", name: "garlic powder" },
      { amount: "1 piece ", name: "lemon" },
      { amount: "½ cup ", name: "butter" },
      { amount: "¼ lb  ", name: "chicken liver" },
    ],
    procedure: [
      "Pour the water in a pan and bring to a boil Add salt and pepper.",
      "Put-in the pig's ears and pork belly then simmer for 40 minutes to 1 hour",
      "Remove the boiled ingredients from the pot then drain excess water",
      "Grill the boiled pig ears and pork belly until done",
      "Chop the pig ears and pork belly into fine pieces",
      "In a wide pan, melt the butter or margarine. Add the onions. Cook until onions are soft.",
      "Put-in the ginger and cook for 2 minutes",
      "Add the chicken liver. Crush the chicken liver while cooking it in the pan.",
      "Add the chopped pig ears and pork belly. Cook for 10 to 12 minutes",
      "Put-in the soy sauce, garlic powder, and chili. Mix well",
      "Add salt and pepper to taste",
      "Put-in the mayonnaise and mix with the other ingredients",
      "Transfer to a serving plate. Top with chopped green onions and raw egg.",
      "Serve hot. Share and Enjoy (add the lemon or calamansi before eating)",
    ],
  },
  {
    id: 11,
    name: "bilo bilo",
    category: "dessert",
    likes: [],
    disLikes: [],
    comments: [],
    mainIngredient: "Coconut Milk",
    img: [
      "https://mnlopsample.files.wordpress.com/2020/02/ginataan.jpg?w=640",
      "https://i.pinimg.com/originals/51/66/c5/5166c5580de78cdafc490c91522b1856.jpg",
      "https://www.foxyfolksy.com/wp-content/uploads/2015/04/bilo-bilo.jpg",
      "https://i.pinimg.com/originals/97/50/20/975020c96e1ae33912465a691bf83a76.jpg",
    ],
    info: `Bilo bilo's origin is in Luzon (Tuguegarao City, Cagayan), which is the northern Philippines Island. 
    There are different recipe versions depending what region in the Philippines it is from. 
    Some recipes call for young coconut meat and some call for adding pandan leaves.`,
    recipe: [
      { amount: "1lb", name: "pig ears" },
      { amount: "1 1/2 lb ", name: "pork belly" },
      { amount: "1 piece ", name: "onion minced" },
      { amount: "3 tablespoons", name: "soy sauce" },
      { amount: "1/4 teaspoon", name: "ground black pepper" },
      { amount: "1 knob ", name: "ginger minced (optional)" },
      { amount: "3 tablespoons ", name: "chili flakes" },
      { amount: "1/2 teaspoon", name: "garlic powder" },
      { amount: "1 piece ", name: "lemon" },
      { amount: "½ cup ", name: "butter" },
      { amount: "¼ lb  ", name: "chicken liver" },
    ],
    procedure: [
      "Pour the water in a pan and bring to a boil Add salt and pepper.",
      "Put-in the pig's ears and pork belly then simmer for 40 minutes to 1 hour",
      "Remove the boiled ingredients from the pot then drain excess water",
      "Grill the boiled pig ears and pork belly until done",
      "Chop the pig ears and pork belly into fine pieces",
      "In a wide pan, melt the butter or margarine. Add the onions. Cook until onions are soft.",
      "Put-in the ginger and cook for 2 minutes",
      "Add the chicken liver. Crush the chicken liver while cooking it in the pan.",
      "Add the chopped pig ears and pork belly. Cook for 10 to 12 minutes",
      "Put-in the soy sauce, garlic powder, and chili. Mix well",
      "Add salt and pepper to taste",
      "Put-in the mayonnaise and mix with the other ingredients",
      "Transfer to a serving plate. Top with chopped green onions and raw egg.",
      "Serve hot. Share and Enjoy (add the lemon or calamansi before eating)",
    ],
  },
  {
    id: 10,
    name: "kalamay",
    category: "dessert",
    likes: [],
    disLikes: [],
    comments: [],
    mainIngredient: "Coconut Milk",
    img: [
      "https://www.kawalingpinoy.com/wp-content/uploads/2019/02/kalamay-gabi-6.jpg",
      "http://www.pinoycookingrecipes.com/uploads/7/6/7/8/7678114/watermark-2019-11-22-13-26-24-1_orig.jpg",
      "https://fyi09.files.wordpress.com/2014/08/kalamay-sunsong-with-latik-or-cooked-coconut-oil-as-topings.jpg",
      "https://i0.wp.com/www.angsarap.net/wp-content/uploads/2021/03/Kalamay-Hati.jpg?ssl=1",
    ],
    info: `Kalamay is made by extracting coconut milk from grated coconuts twice. Glutinous rice is added to 
    the first batch of coconut milk and the mixture is ground into a paste. Brown sugar is added to the second batch of coconut milk and boiled for several hours to make latík. The mixture of ground glutinous rice and coconut milk is 
    then poured into the latík and stirred until the consistency becomes very thick`,
    recipe: [
      { amount: "1lb", name: "pig ears" },
      { amount: "1 1/2 lb ", name: "pork belly" },
      { amount: "1 piece ", name: "onion minced" },
      { amount: "3 tablespoons", name: "soy sauce" },
      { amount: "1/4 teaspoon", name: "ground black pepper" },
      { amount: "1 knob ", name: "ginger minced (optional)" },
      { amount: "3 tablespoons ", name: "chili flakes" },
      { amount: "1/2 teaspoon", name: "garlic powder" },
      { amount: "1 piece ", name: "lemon" },
      { amount: "½ cup ", name: "butter" },
      { amount: "¼ lb  ", name: "chicken liver" },
    ],
    procedure: [
      "Pour the water in a pan and bring to a boil Add salt and pepper.",
      "Put-in the pig's ears and pork belly then simmer for 40 minutes to 1 hour",
      "Remove the boiled ingredients from the pot then drain excess water",
      "Grill the boiled pig ears and pork belly until done",
      "Chop the pig ears and pork belly into fine pieces",
      "In a wide pan, melt the butter or margarine. Add the onions. Cook until onions are soft.",
      "Put-in the ginger and cook for 2 minutes",
      "Add the chicken liver. Crush the chicken liver while cooking it in the pan.",
      "Add the chopped pig ears and pork belly. Cook for 10 to 12 minutes",
      "Put-in the soy sauce, garlic powder, and chili. Mix well",
      "Add salt and pepper to taste",
      "Put-in the mayonnaise and mix with the other ingredients",
      "Transfer to a serving plate. Top with chopped green onions and raw egg.",
      "Serve hot. Share and Enjoy (add the lemon or calamansi before eating)",
    ],
  },
  {
    id: 8,
    name: "bibigka",
    category: "dessert",
    likes: [],
    disLikes: [],
    comments: [],
    mainIngredient: "Coconut Milk",
    img: [
      "http://images.summitmedia-digital.com/yummyph/images/2018/11/08/BibingkaGalapong.jpg",
      "https://www.foxyfolksy.com/wp-content/uploads/2017/12/bibingka-t.jpg",
      "https://i.pinimg.com/736x/6b/df/95/6bdf9526a43f884500651f41556ae2f1.jpg",
      "https://static01.nyt.com/images/2016/11/11/dining/COOKING-BIBINGKA1/COOKING-FILIPINO1-articleLarge.jpg",
    ],
    info: `The shared origins of bibingka from the Philippines and Indonesia is widely acknowledged especially 
    given that the Indonesian bibingka is from Eastern Indonesia, 
    the regions closest to the Philippines with the most closely related cultures.`,
    recipe: [
      { amount: "1lb", name: "pig ears" },
      { amount: "1 1/2 lb ", name: "pork belly" },
      { amount: "1 piece ", name: "onion minced" },
      { amount: "3 tablespoons", name: "soy sauce" },
      { amount: "1/4 teaspoon", name: "ground black pepper" },
      { amount: "1 knob ", name: "ginger minced (optional)" },
      { amount: "3 tablespoons ", name: "chili flakes" },
      { amount: "1/2 teaspoon", name: "garlic powder" },
      { amount: "1 piece ", name: "lemon" },
      { amount: "½ cup ", name: "butter" },
      { amount: "¼ lb  ", name: "chicken liver" },
    ],
    procedure: [
      "Pour the water in a pan and bring to a boil Add salt and pepper.",
      "Put-in the pig's ears and pork belly then simmer for 40 minutes to 1 hour",
      "Remove the boiled ingredients from the pot then drain excess water",
      "Grill the boiled pig ears and pork belly until done",
      "Chop the pig ears and pork belly into fine pieces",
      "In a wide pan, melt the butter or margarine. Add the onions. Cook until onions are soft.",
      "Put-in the ginger and cook for 2 minutes",
      "Add the chicken liver. Crush the chicken liver while cooking it in the pan.",
      "Add the chopped pig ears and pork belly. Cook for 10 to 12 minutes",
      "Put-in the soy sauce, garlic powder, and chili. Mix well",
      "Add salt and pepper to taste",
      "Put-in the mayonnaise and mix with the other ingredients",
      "Transfer to a serving plate. Top with chopped green onions and raw egg.",
      "Serve hot. Share and Enjoy (add the lemon or calamansi before eating)",
    ],
  },
  {
    id: 19,
    name: "Mais con Yelo",
    category: "dessert",
    likes: [],
    disLikes: [],
    comments: [],
    mainIngredient: "Milk",
    img: [
      "https://pilipinasrecipes.com/wp-content/uploads/2018/03/Mais-Con-Yelo.jpg",
      "https://www.thelittleepicurean.com/wp-content/uploads/2020/07/mais-con-yelo-6.jpg",
      "https://simplybakings.com/wp-content/uploads/2021/04/Mais-Con-Yelo.jpg",
      "https://www.savvynana.com/wp-content/uploads/2016/05/Maiz-Con-Hielo-Recipe.jpg",
    ],
    info: `Filipino Mais Con Yelo is a delicious and refreshing summer treat! This layered dessert 
    consists of sweet corn, 
    sweetened shaved ice, and corn flake cereal topped with homemade corn ice cream.`,
    recipe: [
      { amount: "1lb", name: "pig ears" },
      { amount: "1 1/2 lb ", name: "pork belly" },
      { amount: "1 piece ", name: "onion minced" },
      { amount: "3 tablespoons", name: "soy sauce" },
      { amount: "1/4 teaspoon", name: "ground black pepper" },
      { amount: "1 knob ", name: "ginger minced (optional)" },
      { amount: "3 tablespoons ", name: "chili flakes" },
      { amount: "1/2 teaspoon", name: "garlic powder" },
      { amount: "1 piece ", name: "lemon" },
      { amount: "½ cup ", name: "butter" },
      { amount: "¼ lb  ", name: "chicken liver" },
    ],
    procedure: [
      "Pour the water in a pan and bring to a boil Add salt and pepper.",
      "Put-in the pig's ears and pork belly then simmer for 40 minutes to 1 hour",
      "Remove the boiled ingredients from the pot then drain excess water",
      "Grill the boiled pig ears and pork belly until done",
      "Chop the pig ears and pork belly into fine pieces",
      "In a wide pan, melt the butter or margarine. Add the onions. Cook until onions are soft.",
      "Put-in the ginger and cook for 2 minutes",
      "Add the chicken liver. Crush the chicken liver while cooking it in the pan.",
      "Add the chopped pig ears and pork belly. Cook for 10 to 12 minutes",
      "Put-in the soy sauce, garlic powder, and chili. Mix well",
      "Add salt and pepper to taste",
      "Put-in the mayonnaise and mix with the other ingredients",
      "Transfer to a serving plate. Top with chopped green onions and raw egg.",
      "Serve hot. Share and Enjoy (add the lemon or calamansi before eating)",
    ],
  },
];

export const Url = [
  {
    logo: <i className="fas fa-home"></i>,
    title: "HOME",
    links: "/RecipeApp",
  },
  {
    logo: <i className="fas fa-utensils"></i>,
    title: "RECIPE",
    links: "/about-page",
  },
  {
    logo: <i class="fas fa-user"></i>,
    title: "LOG IN",
    links: "/Login",
  },
];

export const bgs = [
  "https://wallpaperaccess.com/full/271679.jpg",
  "https://wallpapercave.com/wp/wp1881532.jpg",
  `https://wallpaperaccess.com/full/271693.jpg`,
  `https://wallpaperaccess.com/full/1306571.jpg`,
  `https://wallpaperaccess.com/full/1537441.jpg`,
];

export const items = [
  {
    id: 1,
    info: `09564-674-190`,
    logo: <BsFillTelephoneFill />,
  },
  {
    id: 2,
    info: "Keifer Ramos",
    logo: <BsMessenger />,
  },
  {
    id: 3,
    info: `KeiferRamos`,
    logo: <BsGithub />,
  },
  {
    id: 4,
    info: `keiferramos2001@gmail.com`,
    logo: <SiGmail />,
  },
];

export default [...meal, ...Dessert];
